### ISSUE TITLE
Move to ArcGIS or Esri?

### ISSUE THREAD

**Issue by joebayles** [Esri/thumbnail-builder-js#11]
Just wondering why you haven't moved this repository over to the organizational accounts?

**Comment by sirws** [comment]
@joebayles, I have never been asked to do so!  Do you think it makes sense to do this?

**Comment by joebayles** [comment]
Well, we share a lot of our stuff (even things that never make it to production) on the ArcGIS (internal) organization, that way people can see it. If it's a neat little tool that you built for anyone that uses Esri products, maybe it should go on the Esri (external) organization, because that'll probably get a lot more traction.

**Comment by sirws** [comment]
Do you know what I need to do to move it?

**Comment by joebayles** [comment]
https://github.com/new

![image](https://cloud.githubusercontent.com/assets/5016557/6877315/22d3d9a6-d48d-11e4-83df-916fbad6707a.png)

Choose ArcGIS. If you don't see those, You need to be added to the ArcGIS team. There are naming conventions for the repositories, I'll have to chase those down...

**Comment by sirws** [comment]
Done!  Finally.  :)
